name: Build and Push to ECR frontend
on:
  push:
    paths:
      - 'frontend/**'
      - 'k8s-manifest/frontend/**'
      - '.github/workflows/build-deploy.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push-APi-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::225748035722:role/OIDC-assign-role
          role-session-name: github-assume
          aws-region: us-west-1

      - name: Login to Amazon ECR # login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image 
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/react-app:${{ github.sha }} ./frontend
          docker tag ${{ vars.ECR_REGISTRY }}/react-app:${{ github.sha }} ${{ vars.ECR_REGISTRY }}/react-app:latest

      - name: Push Docker Image 
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/react-app:${{ github.sha }}
          docker push ${{ vars.ECR_REGISTRY }}/react-app:latest

     
  
  deploy:
    name: Deploy App and ALB Ingress
    needs: build-push-APi-react  # Optional: Run sequentially after job1
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: test-eks
      AWS_REGION: us-east-1
      NAMESPACE: default

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::225748035722:role/OIDC-assign-role
          role-session-name: github-assume
          aws-region: us-west-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-west-1 --name demo6-eks

      - name: Verify Cluster Access
        run: |
          kubectl get nodes
                

      - name: Deployment + Service + Ingress
        run: |
         sed -i 's@CONTAINER_IMAGE@'"${{ vars.ECR_REGISTRY }}/react-app:${{ github.sha }}"'@' k8s/frontend/deployment.yaml
         kubectl apply -f k8s/frontend/deployment.yaml
         kubectl apply -f k8s/frontend/service.yaml
         kubectl apply -f k8s/frontend/ingress.yaml



  